services:
  homebrew_mavros:
    build:
      context: ./mavros
    container_name: com.uflautonomypark.homebrew_mavros.homebrew_mavros
    image: com.uflautonomypark.homebrew_mavros.homebrew_mavros:0.0.1
    network_mode: host
    privileged: true
    env_file:
      - .env
    devices:
      - /dev/ttyFC:/dev/ttyFC
    pid: host
    platform: linux/arm64

